package com.uma.workbench.agent

import java.security.MessageDigest
import java.util.UUID
import java.util.concurrent.ConcurrentHashMap
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.booleanOrNull
import kotlinx.serialization.json.contentOrNull
import kotlinx.serialization.json.intOrNull

data class AgentToolResult(val callId:String,val toolName:String,val resultId:String,val content:String,val startOffset:Int,val endOffsetExclusive:Int,val totalCharacterCount:Int,val complete:Boolean,val nextOffset:Int?,val sha256:String,val elapsedMillis:Long)
data class AgentToolFailure(val callId:String,val toolName:String,val completeError:String,val elapsedMillis:Long)
sealed interface AgentToolOutcome{data class Success(val result:AgentToolResult):AgentToolOutcome;data class Failure(val failure:AgentToolFailure):AgentToolOutcome}
interface AgentToolResultStore{fun put(completeContent:String,toolName:String):String;fun read(resultId:String,offset:Int,limit:Int):AgentToolResultPage}
data class AgentToolResultPage(val resultId:String,val content:String,val startOffset:Int,val endOffsetExclusive:Int,val totalCharacterCount:Int,val complete:Boolean,val nextOffset:Int?,val sha256:String)
data class AgentToolExecutionLimits(val maxCallsPerTurn:Int=32,val pageCharacters:Int=32_768){init{require(maxCallsPerTurn in 1..256){"maxCallsPerTurn 必须在 1..256"};require(pageCharacters in 1..1_000_000){"pageCharacters 必须在 1..1_000_000"}}}
class InMemoryAgentToolResultStore:AgentToolResultStore{private data class Stored(val content:String,val sha256:String);private val values=ConcurrentHashMap<String,Stored>();override fun put(completeContent:String,toolName:String)=UUID.randomUUID().toString().also{values[it]=Stored(completeContent,sha256(completeContent))};override fun read(resultId:String,offset:Int,limit:Int):AgentToolResultPage{val s=values[resultId]?:error("找不到完整工具结果 $resultId");val start=offset.coerceAtLeast(0);val end=(start+limit).coerceAtMost(s.content.length);val page=s.content.substring(start,end);val next=if(end<s.content.length)end else null;return AgentToolResultPage(resultId,page,start,end,s.content.length,next==null,next,s.sha256)};private fun sha256(v:String)=MessageDigest.getInstance("SHA-256").digest(v.toByteArray()).joinToString(""){"%02x".format(it)}}
interface ReadonlyAgentToolDataSource{suspend fun listWorkspaceFiles():String;suspend fun readCurrentFile():String;suspend fun readFile(uri:String):String;suspend fun readFileRange(uri:String,startLine:Int,endLine:Int):String;suspend fun searchWorkspace(query:String,offset:Int,caseSensitive:Boolean):String;suspend fun searchSymbol(query:String,offset:Int):String;suspend fun readIl2CppClass(className:String):String;suspend fun readProtocolRecord(id:String):String;suspend fun readSoSnapshot(endpoint:String?):String;suspend fun readDoc(id:String):String}
class ReadonlyAgentToolExecutor(private val source:ReadonlyAgentToolDataSource,private val limits:AgentToolExecutionLimits=AgentToolExecutionLimits(),private val resultStore:AgentToolResultStore=InMemoryAgentToolResultStore(),private val nowMillis:()->Long=System::currentTimeMillis){
 suspend fun executeTurn(rawCalls:List<AiToolCall>):List<AgentToolOutcome>{val calls=AiToolCallNormalizer.normalize(rawCalls);require(calls.size<=limits.maxCallsPerTurn){"本轮工具调用 ${calls.size} 超过上限 ${limits.maxCallsPerTurn}"};val cache=linkedMapOf<String,AgentToolOutcome>();return calls.map{call->val key=AiToolCallNormalizer.semanticFingerprint(call);cache[key]?.forCall(call)?:execute(call).also{cache[key]=it}}}
 suspend fun execute(call:AiToolCall):AgentToolOutcome=timed(call){args->if(call.name=="read_tool_result")readStoredPage(args)else storePaged(call.name,dispatch(call.name,args))}
 suspend fun executeSpecial(call:AiToolCall,operation:suspend()->AgentSpecialToolPayload):AgentToolOutcome{val started=nowMillis();return try{ReadonlyAgentToolPolicy.validate(call);val payload=operation();require(payload.persistedContent.isNotEmpty());require(payload.modelContent.isNotEmpty());val id=resultStore.put(payload.persistedContent,call.name);val stored=completeStored(id);AgentToolOutcome.Success(AgentToolResult(call.id,call.name,id,payload.modelContent,0,payload.modelContent.length,stored.totalCharacterCount,true,null,stored.sha256,(nowMillis()-started).coerceAtLeast(0)))}catch(e:Throwable){if(e is kotlinx.coroutines.CancellationException)throw e;AgentToolOutcome.Failure(AgentToolFailure(call.id,call.name,e.stackTraceToString(),(nowMillis()-started).coerceAtLeast(0)))}}
 private suspend fun timed(call:AiToolCall,operation:suspend(JsonObject)->AgentToolResultPage):AgentToolOutcome{val started=nowMillis();return try{val args=ReadonlyAgentToolPolicy.validate(call);val page=operation(args);AgentToolOutcome.Success(AgentToolResult(call.id,call.name,page.content.ifEmpty{page.resultId},page.startOffset,page.endOffsetExclusive,page.totalCharacterCount,page.complete,page.nextOffset,page.sha256,(nowMillis()-started).coerceAtLeast(0)))}catch(e:Throwable){if(e is kotlinx.coroutines.CancellationException)throw e;AgentToolOutcome.Failure(AgentToolFailure(call.id,call.name,e.stackTraceToString(),(nowMillis()-started).coerceAtLeast(0)))}}
 private fun storePaged(name:String,content:String):AgentToolResultPage{require(content.isNotEmpty());val id=resultStore.put(content,name);return resultStore.read(id,0,limits.pageCharacters)}
 private fun readStoredPage(a:JsonObject):AgentToolResultPage{val id=a.requiredString("resultId");val offset=a.optionalNonNegativeInt("offset")?:0;val limit=a.optionalPositiveInt("limit")?:limits.pageCharacters;return resultStore.read(id,offset,limit)}
 private fun completeStored(id:String)=resultStore.read(id,0,Int.MAX_VALUE)
 private fun AgentToolOutcome.forCall(call:AiToolCall)=when(this){is AgentToolOutcome.Success->AgentToolOutcome.Success(result.copy(callId=call.id,toolName=call.name,elapsedMillis=0));is AgentToolOutcome.Failure->AgentToolOutcome.Failure(failure.copy(callId=call.id,toolName=call.name,elapsedMillis=0))}
 private suspend fun dispatch(n:String,a:JsonObject):String=when(n){"list_workspace_files"->source.listWorkspaceFiles();"read_current_file"->source.readCurrentFile();"read_file"->source.readFile(a.requiredString("uri"));"read_file_range"->source.readFileRange(a.requiredString("uri"),a.requiredPositiveInt("startLine"),a.requiredPositiveInt("endLine"));"search_workspace"->source.searchWorkspace(a.requiredString("query"),a.optionalNonNegativeInt("offset")?:0,a.optionalBoolean("caseSensitive")?:false);"search_symbol"->source.searchSymbol(a.requiredString("query"),a.optionalNonNegativeInt("offset")?:0);"read_il2cpp_class"->source.readIl2CppClass(a.requiredString("className"));"read_protocol_record"->source.readProtocolRecord(a.requiredString("id"));"read_so_snapshot"->source.readSoSnapshot(a.optionalString("endpoint"));"read_doc"->source.readDoc(a.requiredString("id"));else->error("不允许执行工具 $n")}
 private fun JsonObject.requiredString(n:String)=optionalString(n)?.takeIf{it.isNotBlank()}?:error("参数 $n 必须是非空字符串");private fun JsonObject.optionalString(n:String)=(get(n)as?JsonPrimitive)?.contentOrNull;private fun JsonObject.requiredPositiveInt(n:String)=(get(n)as?JsonPrimitive)?.intOrNull?.takeIf{it>0}?:error("参数 $n 必须是正整数");private fun JsonObject.optionalPositiveInt(n:String):Int?{val v=get(n)?:return null;return(v as?JsonPrimitive)?.intOrNull?.takeIf{it>0}?:error("参数 $n 必须是正整数")};private fun JsonObject.optionalNonNegativeInt(n:String):Int?{val v=get(n)?:return null;return(v as?JsonPrimitive)?.intOrNull?.takeIf{it>=0}?:error("参数 $n 必须是非负整数")};private fun JsonObject.optionalBoolean(n:String):Boolean?{val v=get(n)?:return null;return(v as?JsonPrimitive)?.booleanOrNull?:error("参数 $n 必须是布尔值")}
}
