package com.uma.workbench.agent

import kotlinx.coroutines.currentCoroutineContext
import kotlinx.coroutines.ensureActive
import kotlinx.coroutines.flow.collect

data class ReadonlyAgentRound(val index:Int,val assistantText:String,val toolCalls:List<AiToolCall>,val toolOutcomes:List<AgentToolOutcome>,val model:String?,val usage:AiTokenUsage?)
data class ReadonlyAgentRunResult(val requestId:String,val completeAnswer:String,val rounds:List<ReadonlyAgentRound>,val usage:AiTokenUsage,val model:String?,val messages:List<AiPromptMessage>)
data class ReadonlyAgentLoopLimits(val maxModelRounds:Int=20){init{require(maxModelRounds in 1..100)}}
interface ReadonlyAgentObserver{fun onModelEvent(round:Int,event:AiStreamEvent)=Unit;fun onRoundCompleted(round:ReadonlyAgentRound)=Unit}
class ReadonlyAgentLoop(private val provider:AiStreamingProvider,private val executor:ReadonlyAgentToolExecutor,private val limits:ReadonlyAgentLoopLimits=ReadonlyAgentLoopLimits()){
 suspend fun run(initial:AiGenerationRequest,observer:ReadonlyAgentObserver?=null):ReadonlyAgentRunResult{val messages=initial.messages.toMutableList();val rounds=mutableListOf<ReadonlyAgentRound>();var usage=AiTokenUsage();var model=initial.model
 repeat(limits.maxModelRounds){i->currentCoroutineContext().ensureActive();val calls=AiToolCallAccumulator();val text=StringBuilder();var ru:AiTokenUsage?=null;provider.stream(initial.copy(messages=messages.toList())).collect{e->observer?.onModelEvent(i+1,e);when(e){is AiStreamEvent.TextDelta->text.append(e.completeDelta);is AiStreamEvent.ToolCallDelta->calls.append(e.delta);is AiStreamEvent.Usage->ru=merge(ru,e.usage);is AiStreamEvent.Model->model=e.model;AiStreamEvent.Completed->Unit}};val c=calls.validatedSnapshot();val o=if(c.isEmpty())emptyList()else executor.executeTurn(c);val r=ReadonlyAgentRound(i+1,text.toString(),c,o,model,ru);rounds+=r;observer?.onRoundCompleted(r);ru?.let{usage=add(usage,it)};if(c.isEmpty()){require(text.isNotBlank()){"模型未返回工具调用，也未返回最终答案"};return ReadonlyAgentRunResult(initial.requestId,text.toString(),rounds,usage,model,messages.toList())};require(i+1<limits.maxModelRounds){"Agent 达到最大模型轮次 ${limits.maxModelRounds}"};messages+=AiPromptMessage("assistant",text.toString(),toolCalls=c);c.zip(o).forEach{(call,out)->messages+=AiPromptMessage("tool",out.modelContent(),toolCallId=call.id,toolName=call.name)}};error("Agent 循环异常结束")}
 private fun AgentToolOutcome.modelContent()=when(this){is AgentToolOutcome.Success->buildString{append(result.content);append("\n\n[tool_result_page]\nresultId=${result.resultId}\nrange=${result.startOffset}-${result.endOffsetExclusive}\ntotalCharacterCount=${result.totalCharacterCount}\nsha256=${result.sha256}\ncomplete=${result.complete}\nnextOffset=${result.nextOffset?:""}\nelapsedMillis=${result.elapsedMillis}");if(!result.complete)append("\nUse read_tool_result with this resultId and nextOffset to continue; do not claim the complete result was read yet.")};is AgentToolOutcome.Failure->"[tool_error]\n${failure.completeError}\nelapsedMillis=${failure.elapsedMillis}"}
 private fun merge(a:AiTokenUsage?,b:AiTokenUsage)=if(a==null)b else AiTokenUsage(maxOf(a.inputTokens,b.inputTokens),maxOf(a.outputTokens,b.outputTokens),maxOf(a.totalTokens,b.totalTokens),a.estimated||b.estimated);private fun add(a:AiTokenUsage,b:AiTokenUsage)=AiTokenUsage(a.inputTokens+b.inputTokens,a.outputTokens+b.outputTokens,a.totalTokens+b.totalTokens,a.estimated||b.estimated)
}
