package com.uma.workbench.ui

import android.app.Application
import android.net.Uri
import androidx.lifecycle.AndroidViewModel
import androidx.lifecycle.viewModelScope
import com.uma.workbench.WorkbenchApplication
import com.uma.workbench.agent.*
import com.uma.workbench.data.ConversationEntity
import com.uma.workbench.data.MessageEntity
import java.io.File
import java.util.UUID
import kotlinx.coroutines.*
import kotlinx.coroutines.flow.*

@OptIn(ExperimentalCoroutinesApi::class)
class AiChatViewModel(application: Application) : AndroidViewModel(application) {
    private val app=application as WorkbenchApplication; private val repository=app.repository; private val catalogStore=AiProviderCatalogStore(application)
    private val _catalog=MutableStateFlow(catalogStore.load());val catalog:StateFlow<AiProviderCatalog> =_catalog;private val _conversationId=MutableStateFlow<String?>(null);val conversationId:StateFlow<String?> =_conversationId
    val messages=_conversationId.flatMapLatest{if(it==null)flowOf(emptyList())else repository.messages(it)}.stateIn(viewModelScope,SharingStarted.WhileSubscribed(5_000),emptyList());val activeDocument=ActiveWorkspaceDocumentBridge.document
    private val _attachments=MutableStateFlow<List<WorkspaceContextAttachment>>(emptyList());val attachments=_attachments.asStateFlow();private val _attachmentMessage=MutableStateFlow("");val attachmentMessage=_attachmentMessage.asStateFlow();private val _loadingAttachment=MutableStateFlow(false);val loadingAttachment=_loadingAttachment.asStateFlow();private val _searchPage=MutableStateFlow<WorkspaceSearchPage?>(null);val searchPage=_searchPage.asStateFlow();private val _searching=MutableStateFlow(false);val searching=_searching.asStateFlow();private val _generation=MutableStateFlow(AiGenerationState());val generation=_generation.asStateFlow();private val _agentRounds=MutableStateFlow<List<ReadonlyAgentRound>>(emptyList());val agentRounds=_agentRounds.asStateFlow()
    private var job:Job?=null;private var lastQuery="";private var lastCase=false;private val search=WorkspaceReadonlySearch(WorkspaceDocumentTextReader{readText(it.uri)},WorkspaceSearchLimits(maxDocuments=100,maxCharactersPerDocument=2_000_000,maxMatchesPerPage=100));private val provider=CatalogAiStreamingProvider(::profile)
    private fun profile():AiProviderProfile?{_catalog.value=catalogStore.load();val s=_catalog.value.defaultModel?:return null;return _catalog.value.providers.firstOrNull{it.id==s.providerId}}
    fun refreshConfiguration(){_catalog.value=catalogStore.load()};fun newConversation(){if(job?.isActive==true)return;_conversationId.value=null;_attachments.value=emptyList();_agentRounds.value=emptyList();_generation.value=AiGenerationState()}
    fun searchWorkspace(q:String,caseSensitive:Boolean=false,offset:Int=0){val d=activeDocument.value?:return;if(q.isBlank())return;viewModelScope.launch{_searching.value=true;lastQuery=q;lastCase=caseSensitive;runCatching{val r=app.database.recentFiles().observe(d.workspaceId).first();val s=repository.sources().first().filter{it.workspaceId==d.workspaceId};search.search(buildList{add(WorkspaceSearchDocument(d.workspaceId,d.uri,d.title));r.forEach{add(WorkspaceSearchDocument(it.workspaceId,it.uri,it.name))};s.forEach{add(WorkspaceSearchDocument(d.workspaceId,it.uri,it.name))}},q,offset,caseSensitive)}.onSuccess{_searchPage.value=it;_attachmentMessage.value="匹配 ${it.totalMatches}"}.onFailure{_attachmentMessage.value=it.stackTraceToString()};_searching.value=false}}
    fun nextSearchPage(){_searchPage.value?.nextOffset?.let{searchWorkspace(lastQuery,lastCase,it)}}
    fun attachSearchMatch(m:WorkspaceSearchMatch){viewModelScope.launch{_loadingAttachment.value=true;runCatching{WorkspaceContextAttachmentFactory.fromText(m.workspaceId,m.uri,m.title,readText(m.uri),m.lineNumber,m.lineNumber)}.onSuccess{_attachments.value+=it}.onFailure{_attachmentMessage.value=it.stackTraceToString()};_loadingAttachment.value=false}}
    fun attachCurrentFileRange(s:Int,e:Int){val d=activeDocument.value?:return;if(s<1||e<s)return;viewModelScope.launch{_loadingAttachment.value=true;runCatching{WorkspaceContextAttachmentFactory.fromText(d.workspaceId,d.uri,d.title,readText(d.uri),s,e)}.onSuccess{_attachments.value+=it}.onFailure{_attachmentMessage.value=it.stackTraceToString()};_loadingAttachment.value=false}}
    private suspend fun readText(uri:String)=withContext(Dispatchers.IO){app.contentResolver.openInputStream(Uri.parse(uri))?.use{String(it.readBytes(),Charsets.UTF_8)}?:error("无法打开 $uri")};fun removeAttachment(id:String){_attachments.value=_attachments.value.filterNot{it.id==id}}
    fun send(text:String){if(text.isBlank()||job?.isActive==true)return;refreshConfiguration();val selection=_catalog.value.defaultModel?:return;val d=activeDocument.value?:return
        job=viewModelScope.launch{val chosen=_attachments.value.toList();val prompt=WorkspaceContextPromptComposer.compose(text,chosen);val conv=ensureConversation(text);val history=messages.value.map{AiPromptMessage(it.role.lowercase(),it.content)}+AiPromptMessage("user",prompt);repository.addMessage(MessageEntity(UUID.randomUUID().toString(),conv,null,null,repository.nextMessageSequence(conv),"user",text,createdAt=System.currentTimeMillis(),toolCallsJson=WorkspaceContextPromptComposer.metadataJson(chosen)));val requestId=UUID.randomUUID().toString();_attachments.value=emptyList();_agentRounds.value=emptyList();_generation.value=AiGenerationState(AiGenerationPhase.GENERATING,requestId,model=selection.modelId)
            val source=AndroidReadonlyAgentToolDataSource(app,app.database,d.workspaceId,{activeDocument.value});val root=File(app.filesDir,"agent-tool-results/${d.workspaceId}/$conv");val store=FileAgentToolResultStore(root,d.workspaceId,conv);val loop=ReadonlyAgentLoop(provider,ReadonlyAgentToolExecutor(source,resultStore=store))
            try{val result=loop.run(AiGenerationRequest(requestId,history,selection.modelId,ReadonlyAgentToolSchemas.openAiCompatible),object:ReadonlyAgentObserver{override fun onModelEvent(round:Int,event:AiStreamEvent){if(event is AiStreamEvent.TextDelta)_generation.value=_generation.value.copy(completeText=_generation.value.completeText+event.completeDelta)};override fun onRoundCompleted(round:ReadonlyAgentRound){_agentRounds.value+=round;if(round.toolCalls.isNotEmpty())_generation.value=_generation.value.copy(completeText="",toolCalls=round.toolCalls)}});_generation.value=_generation.value.copy(phase=AiGenerationPhase.COMPLETED,completeText=result.completeAnswer,usage=result.usage,model=result.model);repository.addMessage(MessageEntity(UUID.randomUUID().toString(),conv,requestId,requestId,repository.nextMessageSequence(conv),"assistant",result.completeAnswer,"COMPLETED",System.currentTimeMillis(),toolCallsJson=AgentRunPresentation.toJson(result.rounds),tokenCount=result.usage.totalTokens.coerceAtMost(Int.MAX_VALUE.toLong()).toInt(),modelUsed=result.model?:selection.modelId))}catch(c:CancellationException){_generation.value=_generation.value.copy(phase=AiGenerationPhase.CANCELLED);throw c}catch(e:Throwable){_generation.value=_generation.value.copy(phase=AiGenerationPhase.FAILED,error=e.stackTraceToString())}finally{job=null}}
    }
    fun interrupt(){job?.cancel(CancellationException("用户停止 Agent"))};private suspend fun ensureConversation(t:String):String{_conversationId.value?.let{return it};val now=System.currentTimeMillis();val id=UUID.randomUUID().toString();repository.createConversation(ConversationEntity(id,t.take(40),now,now,workspaceId=activeDocument.value?.workspaceId));_conversationId.value=id;return id}
}
object AgentRunPresentation{fun toJson(rounds:List<ReadonlyAgentRound>)=rounds.joinToString(prefix="[",postfix="]"){"{\"round\":${it.index},\"calls\":${it.toolCalls.size}}"}}
