package com.uma.workbench.ui

import android.app.Application
import android.net.Uri
import androidx.lifecycle.AndroidViewModel
import androidx.lifecycle.viewModelScope
import com.uma.workbench.WorkbenchApplication
import com.uma.workbench.agent.*
import com.uma.workbench.data.ConversationEntity
import com.uma.workbench.data.MessageEntity
import java.io.File
import java.util.UUID
import kotlinx.coroutines.*
import kotlinx.coroutines.flow.*

data class PersistedSubAgentRun(val messageId:String,val report:PersistedSubAgentReportRef)
@OptIn(ExperimentalCoroutinesApi::class)
class AiChatViewModel(application:Application):AndroidViewModel(application){
 private val app=application as WorkbenchApplication;private val repository=app.repository;private val store=AiProviderCatalogStore(application);private val _catalog=MutableStateFlow(store.load());val catalog:StateFlow<AiProviderCatalog> =_catalog;private val _conversationId=MutableStateFlow<String?>(null);val conversationId:StateFlow<String?> =_conversationId;val activeDocument=ActiveWorkspaceDocumentBridge.document
 val conversations=activeDocument.flatMapLatest{d->if(d==null)flowOf(emptyList())else repository.conversations(d.workspaceId)}.stateIn(viewModelScope,SharingStarted.WhileSubscribed(5_000),emptyList());val messages=_conversationId.flatMapLatest{if(it==null)flowOf(emptyList())else repository.messages(it)}.stateIn(viewModelScope,SharingStarted.WhileSubscribed(5_000),emptyList())
 private val _attachments=MutableStateFlow<List<WorkspaceContextAttachment>>(emptyList());val attachments=_attachments.asStateFlow();private val _attachmentMessage=MutableStateFlow("");val attachmentMessage=_attachmentMessage.asStateFlow();private val _loadingAttachment=MutableStateFlow(false);val loadingAttachment=_loadingAttachment.asStateFlow();private val _searchPage=MutableStateFlow<WorkspaceSearchPage?>(null);val searchPage=_searchPage.asStateFlow();private val _searching=MutableStateFlow(false);val searching=_searching.asStateFlow();private val _generation=MutableStateFlow(AiGenerationState());val generation=_generation.asStateFlow();private val _agentRounds=MutableStateFlow<List<ReadonlyAgentRound>>(emptyList());val agentRounds=_agentRounds.asStateFlow();val persistedSubAgentRuns=messages.map{list->list.flatMap{m->AgentRunMetadata.subAgentReportRefs(m.toolCallsJson).map{PersistedSubAgentRun(m.id,it)}}}.stateIn(viewModelScope,SharingStarted.WhileSubscribed(5_000),emptyList())
 private var job:Job?=null;private var lastQuery="";private var lastCase=false;private val search=WorkspaceReadonlySearch(WorkspaceDocumentTextReader{readText(it.uri)},WorkspaceSearchLimits(maxDocuments=100,maxCharactersPerDocument=2_000_000,maxMatchesPerPage=100));private val provider=CatalogAiStreamingProvider(::profile)
 init{viewModelScope.launch{activeDocument.map{it?.workspaceId}.distinctUntilChanged().collect{ws->val current=_conversationId.value?.let{repository.conversation(it)};if(current?.workspaceId!=ws){_conversationId.value=null;_agentRounds.value=emptyList();_generation.value=AiGenerationState()}}}}
 private fun profile():AiProviderProfile?{_catalog.value=store.load();val s=_catalog.value.defaultModel?:return null;return _catalog.value.providers.firstOrNull{it.id==s.providerId}}
 fun refreshConfiguration(){_catalog.value=store.load()};fun newConversation(){if(job?.isActive==true)return;_conversationId.value=null;_attachments.value=emptyList();_agentRounds.value=emptyList();_generation.value=AiGenerationState()};fun openConversation(id:String){if(job?.isActive==true)return;viewModelScope.launch{val d=activeDocument.value?:return@launch;val c=repository.conversation(id)?:return@launch;if(c.workspaceId!=d.workspaceId){_attachmentMessage.value="拒绝打开其他工作区的对话";return@launch};_conversationId.value=id;_attachments.value=emptyList();_agentRounds.value=emptyList();_generation.value=AiGenerationState()}}
 fun readPersistedToolResult(resultId:String,offset:Int=0,limit:Int=32_768):AgentToolResultPage{val d=activeDocument.value?:error("当前没有工作区");val c=_conversationId.value?:error("当前没有对话");return FileAgentToolResultStore(File(app.filesDir,"agent-tool-results/${d.workspaceId}/$c"),d.workspaceId,c).read(resultId,offset,limit.coerceIn(1,1_000_000))}
 fun searchWorkspace(q:String,caseSensitive:Boolean=false,offset:Int=0){val d=activeDocument.value?:return;if(q.isBlank())return;viewModelScope.launch{_searching.value=true;lastQuery=q;lastCase=caseSensitive;runCatching{val r=app.database.recentFiles().observe(d.workspaceId).first();val s=repository.sources().first().filter{it.workspaceId==d.workspaceId};search.search(buildList{add(WorkspaceSearchDocument(d.workspaceId,d.uri,d.title));r.forEach{add(WorkspaceSearchDocument(it.workspaceId,it.uri,it.name))};s.forEach{add(WorkspaceSearchDocument(d.workspaceId,it.uri,it.name))}},q,offset,caseSensitive)}.onSuccess{_searchPage.value=it}.onFailure{_attachmentMessage.value=it.stackTraceToString()};_searching.value=false}}
 fun nextSearchPage(){_searchPage.value?.nextOffset?.let{searchWorkspace(lastQuery,lastCase,it)}};fun attachSearchMatch(m:WorkspaceSearchMatch){viewModelScope.launch{_loadingAttachment.value=true;runCatching{WorkspaceContextAttachmentFactory.fromText(m.workspaceId,m.uri,m.title,readText(m.uri),m.lineNumber,m.lineNumber)}.onSuccess{_attachments.value+=it}.onFailure{_attachmentMessage.value=it.stackTraceToString()};_loadingAttachment.value=false}};fun attachCurrentFileRange(s:Int,e:Int){val d=activeDocument.value?:return;if(s<1||e<s)return;viewModelScope.launch{_loadingAttachment.value=true;runCatching{WorkspaceContextAttachmentFactory.fromText(d.workspaceId,d.uri,d.title,readText(d.uri),s,e)}.onSuccess{_attachments.value+=it}.onFailure{_attachmentMessage.value=it.stackTraceToString()};_loadingAttachment.value=false}}
 private suspend fun readText(uri:String)=withContext(Dispatchers.IO){app.contentResolver.openInputStream(Uri.parse(uri))?.use{String(it.readBytes(),Charsets.UTF_8)}?:error("无法打开 $uri")};fun removeAttachment(id:String){_attachments.value=_attachments.value.filterNot{it.id==id}}
 fun send(text:String){if(text.isBlank()||job?.isActive==true)return;refreshConfiguration();val selection=_catalog.value.defaultModel?:return;val d=activeDocument.value?:return;job=viewModelScope.launch{val chosen=_attachments.value.toList();val conv=ensureConversation(text);val history=messages.value.map{AiPromptMessage(it.role.lowercase(),it.content)}+AiPromptMessage("user",WorkspaceContextPromptComposer.compose(text,chosen));repository.addMessage(MessageEntity(UUID.randomUUID().toString(),conv,null,null,repository.nextMessageSequence(conv),"user",text,createdAt=System.currentTimeMillis(),toolCallsJson=WorkspaceContextPromptComposer.metadataJson(chosen)));val requestId=UUID.randomUUID().toString();_attachments.value=emptyList();_agentRounds.value=emptyList();_generation.value=AiGenerationState(AiGenerationPhase.GENERATING,requestId,model=selection.modelId);val resultStore=FileAgentToolResultStore(File(app.filesDir,"agent-tool-results/${d.workspaceId}/$conv"),d.workspaceId,conv);val source=AndroidReadonlyAgentToolDataSource(app,app.database,d.workspaceId,{activeDocument.value});val loop=ReadonlyAgentRuntimeFactory(provider,source,resultStore).createRootLoop();try{val result=loop.run(AiGenerationRequest(requestId,history,selection.modelId,ReadonlyAgentToolSchemas.openAiCompatible),object:ReadonlyAgentObserver{override fun onModelEvent(round:Int,event:AiStreamEvent){if(event is AiStreamEvent.TextDelta)_generation.value=_generation.value.copy(completeText=_generation.value.completeText+event.completeDelta)};override fun onRoundCompleted(round:ReadonlyAgentRound){_agentRounds.value+=round;if(round.toolCalls.isNotEmpty())_generation.value=_generation.value.copy(completeText="")}});_generation.value=_generation.value.copy(phase=AiGenerationPhase.COMPLETED,completeText=result.completeAnswer,usage=result.usage,model=result.model);repository.addMessage(MessageEntity(UUID.randomUUID().toString(),conv,requestId,requestId,repository.nextMessageSequence(conv),"assistant",result.completeAnswer,"COMPLETED",System.currentTimeMillis(),toolCallsJson=AgentRunMetadata.toJson(result.rounds),tokenCount=result.usage.totalTokens.coerceAtMost(Int.MAX_VALUE.toLong()).toInt(),modelUsed=result.model?:selection.modelId))}catch(c:CancellationException){_generation.value=_generation.value.copy(phase=AiGenerationPhase.CANCELLED);throw c}catch(e:Throwable){_generation.value=_generation.value.copy(phase=AiGenerationPhase.FAILED,error=e.stackTraceToString())}finally{job=null}}}
 fun interrupt(){job?.cancel(CancellationException("用户停止 Agent"))};private suspend fun ensureConversation(t:String):String{_conversationId.value?.let{return it};val now=System.currentTimeMillis();val id=UUID.randomUUID().toString();repository.createConversation(ConversationEntity(id,t.take(40),now,now,workspaceId=activeDocument.value?.workspaceId));_conversationId.value=id;return id}
}
