package com.uma.workbench.ui

import android.app.Application
import android.net.Uri
import androidx.lifecycle.AndroidViewModel
import androidx.lifecycle.viewModelScope
import com.uma.workbench.WorkbenchApplication
import com.uma.workbench.agent.*
import com.uma.workbench.data.ConversationEntity
import com.uma.workbench.data.GenerationRunEntity
import com.uma.workbench.data.MessageEntity
import com.uma.workbench.diagnostics.WorkbenchErrorMapper
import java.io.File
import java.util.UUID
import kotlinx.coroutines.*
import kotlinx.coroutines.flow.*

data class PersistedSubAgentRun(val messageId:String,val report:PersistedSubAgentReportRef)
@OptIn(ExperimentalCoroutinesApi::class)
class AiChatViewModel(application:Application):AndroidViewModel(application){
 private val app=application as WorkbenchApplication;private val repository=app.repository;private val store=AiProviderCatalogStore(application);private val _catalog=MutableStateFlow(store.load());val catalog:StateFlow<AiProviderCatalog> =_catalog;private val _conversationId=MutableStateFlow<String?>(null);val conversationId:StateFlow<String?> =_conversationId;val activeDocument=ActiveWorkspaceDocumentBridge.document
 val conversations=activeDocument.flatMapLatest{d->if(d==null)flowOf(emptyList())else repository.conversations(d.workspaceId)}.stateIn(viewModelScope,SharingStarted.WhileSubscribed(5_000),emptyList());val messages=_conversationId.flatMapLatest{if(it==null)flowOf(emptyList())else repository.messages(it)}.stateIn(viewModelScope,SharingStarted.WhileSubscribed(5_000),emptyList())
 private val _attachments=MutableStateFlow<List<WorkspaceContextAttachment>>(emptyList());val attachments=_attachments.asStateFlow();private val _attachmentMessage=MutableStateFlow("");val attachmentMessage=_attachmentMessage.asStateFlow();private val _loadingAttachment=MutableStateFlow(false);val loadingAttachment=_loadingAttachment.asStateFlow();private val _searchPage=MutableStateFlow<WorkspaceSearchPage?>(null);val searchPage=_searchPage.asStateFlow();private val _searching=MutableStateFlow(false);val searching=_searching.asStateFlow();private val _generation=MutableStateFlow(AiGenerationState());val generation=_generation.asStateFlow();private val _agentRounds=MutableStateFlow<List<ReadonlyAgentRound>>(emptyList());val agentRounds=_agentRounds.asStateFlow();val persistedSubAgentRuns=messages.map{list->list.flatMap{m->AgentRunMetadata.subAgentReportRefs(m.toolCallsJson).map{PersistedSubAgentRun(m.id,it)}}}.stateIn(viewModelScope,SharingStarted.WhileSubscribed(5_000),emptyList())
 private var job:Job?=null;private val search=WorkspaceReadonlySearch(WorkspaceDocumentTextReader{readText(it.uri)});private val provider=CatalogAiStreamingProvider(::profile)
 init{viewModelScope.launch{activeDocument.map{it?.workspaceId}.distinctUntilChanged().collect{ws->val current=_conversationId.value?.let{repository.conversation(it)};if(current?.workspaceId!=ws){_conversationId.value=null;_agentRounds.value=emptyList();_generation.value=AiGenerationState()}}}}
 private fun profile():AiProviderProfile?{_catalog.value=store.load();val s=_catalog.value.defaultModel?:return null;return _catalog.value.providers.firstOrNull{it.id==s.providerId}}
 fun refreshConfiguration(){_catalog.value=store.load()};fun newConversation(){if(job?.isActive==true)return;_conversationId.value=null;_attachments.value=emptyList();_agentRounds.value=emptyList();_generation.value=AiGenerationState()};fun openConversation(id:String){if(job?.isActive==true)return;viewModelScope.launch{val d=activeDocument.value?:return@launch;val c=repository.conversation(id)?:return@launch;if(c.workspaceId!=d.workspaceId){_attachmentMessage.value="拒绝打开其他工作区的对话";return@launch};_conversationId.value=id;_attachments.value=emptyList();_agentRounds.value=emptyList();_generation.value=AiGenerationState()}}
 fun readPersistedToolResult(resultId:String,offset:Int=0,limit:Int=32_768):AgentToolResultPage{val d=activeDocument.value?:error("当前没有工作区");val c=_conversationId.value?:error("当前没有对话");return FileAgentToolResultStore(File(app.filesDir,"agent-tool-results/${d.workspaceId}/$c"),d.workspaceId,c).read(resultId,offset,limit.coerceIn(1,1_000_000))}
 fun searchWorkspace(q:String,caseSensitive:Boolean=false,offset:Int=0){val d=activeDocument.value?:return;if(q.isBlank())return;viewModelScope.launch{_searching.value=true;runCatching{val r=app.database.recentFiles().observe(d.workspaceId).first();val s=repository.sources().first().filter{it.workspaceId==d.workspaceId};search.search(buildList{add(WorkspaceSearchDocument(d.workspaceId,d.uri,d.title));r.forEach{add(WorkspaceSearchDocument(it.workspaceId,it.uri,it.name))};s.forEach{add(WorkspaceSearchDocument(it.workspaceId?:d.workspaceId,it.uri,it.name))}},q,0,caseSensitive)}.onSuccess{_searchPage.value=it}.onFailure{_attachmentMessage.value=WorkbenchErrorMapper.map(it,0).userFacing.displayText};_searching.value=false}}
 fun nextSearchPage(){};fun attachSearchMatch(m:WorkspaceSearchMatch){viewModelScope.launch{_loadingAttachment.value=true;runCatching{WorkspaceContextAttachmentFactory.fromCompleteText(m.workspaceId,m.uri,m.title,readText(m.uri))}.onSuccess{_attachments.value+=it}.onFailure{_attachmentMessage.value=WorkbenchErrorMapper.map(it,0).userFacing.displayText};_loadingAttachment.value=false}};fun attachCurrentFileRange(s:Int,e:Int){val d=activeDocument.value?:return;viewModelScope.launch{_loadingAttachment.value=true;runCatching{WorkspaceContextAttachmentFactory.fromCompleteText(d.workspaceId,d.uri,d.title,readText(d.uri))}.onSuccess{_attachments.value+=it}.onFailure{_attachmentMessage.value=WorkbenchErrorMapper.map(it,0).userFacing.displayText};_loadingAttachment.value=false}}
 private suspend fun readText(uri:String)=withContext(Dispatchers.IO){app.contentResolver.openInputStream(Uri.parse(uri))?.use{String(it.readBytes(),Charsets.UTF_8)}?:error("无法打开 $uri")};fun removeAttachment(id:String){_attachments.value=_attachments.value.filterNot{it.id==id}}
 fun send(text:String){if(text.isBlank()||job?.isActive==true)return;refreshConfiguration();val selection=_catalog.value.defaultModel?:return;val d=activeDocument.value?:return;job=viewModelScope.launch{val chosen=_attachments.value.toList();val conv=ensureConversation(text);val history=messages.value.map{AiPromptMessage(it.role.lowercase(),it.content)}+AiPromptMessage("user",WorkspaceContextPromptComposer.compose(text,chosen));repository.addMessage(MessageEntity(UUID.randomUUID().toString(),conv,null,null,repository.nextMessageSequence(conv),"user",text,createdAt=System.currentTimeMillis(),toolCallsJson=WorkspaceContextPromptComposer.metadataJson(chosen)));val requestId=UUID.randomUUID().toString();_attachments.value=emptyList();_agentRounds.value=emptyList();_generation.value=AiGenerationState(AiGenerationPhase.GENERATING,requestId,model=selection.modelId);val loop=AiChatRuntimeFactory.create(app,provider,d.workspaceId,conv);var receivedText="";try{val result=loop.run(AiGenerationRequest(requestId,history,selection.modelId,ReadonlyAgentToolSchemas.openAiCompatible),object:ReadonlyAgentObserver{override fun onModelEvent(round:Int,event:AiStreamEvent){if(event is AiStreamEvent.TextDelta){receivedText+=event.completeDelta;_generation.value=_generation.value.copy(completeText=receivedText,partialCharacterCount=receivedText.length)}};override fun onRoundCompleted(round:ReadonlyAgentRound){_agentRounds.value+=round;if(round.toolCalls.isNotEmpty())_generation.value=_generation.value.copy(completeText="")}});_generation.value=_generation.value.copy(phase=AiGenerationPhase.COMPLETED,completeText=result.completeAnswer,usage=result.usage,model=result.model);repository.addMessage(MessageEntity(UUID.randomUUID().toString(),conv,requestId,requestId,repository.nextMessageSequence(conv),"assistant",result.completeAnswer,"COMPLETED",System.currentTimeMillis(),toolCallsJson=AgentRunMetadata.toJson(result.rounds),tokenCount=result.usage.totalTokens.coerceAtMost(Int.MAX_VALUE.toLong()).toInt(),modelUsed=result.model?:selection.modelId))}catch(c:CancellationException){_generation.value=_generation.value.copy(phase=AiGenerationPhase.CANCELLED);throw c}catch(e:Throwable){if(isNetworkError(e)&&receivedText.isNotEmpty()){saveGenerationSnapshot(requestId,conv,d.workspaceId,selection.modelId,text,receivedText,history);_generation.value=_generation.value.copy(phase=AiGenerationPhase.WAITING_FOR_NETWORK,partialCharacterCount=receivedText.length)}else{_generation.value=_generation.value.copy(phase=AiGenerationPhase.FAILED,error=WorkbenchErrorMapper.map(e,receivedText.length).userFacing.displayText)}}finally{job=null}}}
 private fun isNetworkError(e:Throwable):Boolean{val s=e.toString();return s.contains("Software caused connection abort",true)||s.contains("Connection reset",true)||e is java.net.SocketException||e is java.net.ConnectException||e is java.net.UnknownHostException||e is java.net.SocketTimeoutException||e is javax.net.ssl.SSLException}
 private suspend fun saveGenerationSnapshot(requestId:String,convId:String,wsId:String,model:String,userMessage:String,receivedText:String,history:List<AiPromptMessage>){val now=System.currentTimeMillis();val snapshot=GenerationRunEntity(requestId=requestId,conversationId=convId,workspaceId=wsId,model=model,systemPrompt=null,userMessage=userMessage,messagesSnapshot=history.joinToString("\n"){it.role+":"+it.content},receivedText=receivedText,lastEventId=null,toolCallsJson=null,usageJson=null,status="WAITING_FOR_NETWORK",createdAt=now,updatedAt=now);app.database.generationRuns().upsert(snapshot)}
 fun retryAfterNetwork(){val current=_generation.value;if(current.phase!=AiGenerationPhase.WAITING_FOR_NETWORK)return;job=viewModelScope.launch{_generation.value=_generation.value.copy(phase=AiGenerationPhase.RESUMING);try{val run=app.database.generationRuns().get(current.requestId?:"")?:error("找不到中断的生成记录");_generation.value=_generation.value.copy(phase=AiGenerationPhase.COMPLETED,completeText=run.receivedText);repository.addMessage(MessageEntity(UUID.randomUUID().toString(),run.conversationId,run.requestId,run.requestId,repository.nextMessageSequence(run.conversationId),"assistant",run.receivedText,"INTERRUPTED",System.currentTimeMillis(),modelUsed=run.model));app.database.generationRuns().updateStatus(run.requestId,"COMPLETED",System.currentTimeMillis())}catch(e:Throwable){_generation.value=_generation.value.copy(phase=AiGenerationPhase.FAILED,error=WorkbenchErrorMapper.map(e,0).userFacing.displayText)}finally{job=null}}}
 fun stopAndKeep(){if(_generation.value.phase==AiGenerationPhase.WAITING_FOR_NETWORK||_generation.value.phase==AiGenerationPhase.RESUMING){job?.cancel();_generation.value=_generation.value.copy(phase=AiGenerationPhase.INTERRUPTED)}}
 fun interrupt(){job?.cancel(CancellationException("用户停止 Agent"))};private suspend fun ensureConversation(t:String):String{_conversationId.value?.let{return it};val now=System.currentTimeMillis();val id=UUID.randomUUID().toString();repository.createConversation(ConversationEntity(id,t,now,now,workspaceId=activeDocument.value?.workspaceId));_conversationId.value=id;return id}

 private val _selection=MutableStateFlow(ConversationSelectionState());val selection:StateFlow<ConversationSelectionState> =_selection.asStateFlow()
 fun enterSelection(conversationId:String?){_selection.value=_selection.value.enter(conversationId)}
 fun toggleSelection(conversationId:String){if(_selection.value.selecting)_selection.value=_selection.value.toggle(conversationId)}
 fun selectAllVisible(ids:List<String>){_selection.value=_selection.value.selectAll(ids)}
 fun clearSelection(){_selection.value=_selection.value.clearSelection()}
 fun exitSelection(){_selection.value=_selection.value.exit()}
 fun deleteSelectedConversations()=viewModelScope.launch{val wsId=activeDocument.value?.workspaceId;val ids=_selection.value.selectedIds;if(ids.isEmpty()){_selection.value=_selection.value.copy(error="没有选中的对话");return@launch};_selection.value=_selection.value.copy(deleting=true,error=null);try{if(wsId!=null){repository.deleteConversations(wsId,ids)};_selection.value=ConversationSelectionState();if(_conversationId.value in ids){_conversationId.value=null}}catch(e:Throwable){_selection.value=_selection.value.copy(deleting=false,error=WorkbenchErrorMapper.map(e,0).userFacing.displayText)}}
}
