package com.uma.workbench.ui

import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.lazy.rememberLazyListState
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import com.uma.workbench.agent.*

@Composable fun AiChatScreen(vm:AiChatViewModel,openConfiguration:()->Unit){val messages by vm.messages.collectAsStateWithLifecycle();val generation by vm.generation.collectAsStateWithLifecycle();val catalog by vm.catalog.collectAsStateWithLifecycle();val document by vm.activeDocument.collectAsStateWithLifecycle();val attachments by vm.attachments.collectAsStateWithLifecycle();val rounds by vm.agentRounds.collectAsStateWithLifecycle();val conversations by vm.conversations.collectAsStateWithLifecycle();val currentId by vm.conversationId.collectAsStateWithLifecycle();var input by remember{mutableStateOf("")};var history by remember{mutableStateOf(false)};var range by remember{mutableStateOf(false)};var search by remember{mutableStateOf(false)};val state=rememberLazyListState();val selection=catalog.defaultModel;val live=generation.phase==AiGenerationPhase.GENERATING
 LaunchedEffect(messages.size,rounds.size,generation.completeText){val n=messages.size+rounds.size+if(live)1 else 0;if(n>0)state.scrollToItem(n-1)}
 Column(Modifier.fillMaxSize().padding(10.dp)){Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Column{Text("AI 只读 Agent",style=MaterialTheme.typography.titleLarge);Text(document?.title?:"未打开工作区文件",style=MaterialTheme.typography.labelSmall)};Row{TextButton({history=true},enabled=document!=null&&!live){Icon(Icons.Default.History,null);Text("历史")};TextButton(vm::newConversation,enabled=!live){Icon(Icons.Default.AddComment,null);Text("新对话")};TextButton(openConfiguration){Text("配置")}}}
 LazyColumn(Modifier.weight(1f).fillMaxWidth(),state=state,verticalArrangement=Arrangement.spacedBy(8.dp)){items(messages,key={it.id}){m->Card(Modifier.fillMaxWidth()){Column(Modifier.padding(10.dp)){Text(if(m.role.equals("user",true))"你" else "AI",style=MaterialTheme.typography.labelMedium);Text(m.content);if(!m.role.equals("user",true))Text(listOfNotNull(m.status,m.modelUsed,m.tokenCount?.let{"Token $it"}).joinToString(" · "),style=MaterialTheme.typography.labelSmall)}}};items(rounds,key={"r-${it.index}"}){AgentRound(it)};if(live)item("live"){Card(Modifier.fillMaxWidth()){Column(Modifier.padding(10.dp)){Text("AI · 第 ${rounds.size+1} 轮");Text(generation.completeText.ifEmpty{"等待模型或执行只读工具…"})}}}}
 Row(Modifier.fillMaxWidth()){TextButton({search=true},enabled=document!=null&&!live){Icon(Icons.Default.Search,null);Text("搜索")};TextButton({range=true},enabled=document!=null&&!live){Icon(Icons.Default.AttachFile,null);Text("文件范围")};Text("附件 ${attachments.size}",style=MaterialTheme.typography.labelSmall,modifier=Modifier.padding(12.dp))}
 attachments.forEach{x->AssistChip({vm.removeAttachment(x.id)},{Text("${x.title} L${x.startLine}-${x.endLine} · ${x.sentCharacterCount}/${x.completeCharacterCount}")},trailingIcon={Icon(Icons.Default.Close,null)})}
 Row(Modifier.fillMaxWidth(),verticalAlignment=androidx.compose.ui.Alignment.CenterVertically){OutlinedTextField(input,{input=it},label={Text("发送消息")},enabled=generation.canSend,modifier=Modifier.weight(1f),maxLines=5);IconButton({if(generation.canInterrupt)vm.interrupt()else if(input.isNotBlank()&&selection!=null){vm.send(input);input=""}},enabled=generation.canInterrupt||(input.isNotBlank()&&selection!=null)){Icon(if(generation.canInterrupt)Icons.Default.Stop else Icons.Default.Send,null)}}}
 if(history)AlertDialog({history=false},{TextButton({history=false}){Text("关闭")}},title={Text("当前工作区对话")},text={LazyColumn(Modifier.fillMaxWidth().heightIn(max=480.dp)){if(conversations.isEmpty())item{Text("暂无历史对话")};items(conversations,key={it.id}){c->ListItem(headlineContent={Text(c.title)},supportingContent={Text("${c.agentMode} · ${c.updatedAt}")},leadingContent={if(c.id==currentId)Icon(Icons.Default.Chat,null)},modifier=Modifier.fillMaxWidth());HorizontalDivider();LaunchedEffect(c.id){ };Row(Modifier.fillMaxWidth()){TextButton({vm.openConversation(c.id);history=false}){Text(if(c.id==currentId)"当前对话" else "打开")}}}}})
 if(range)RangeDialog2(document,{range=false}){a,b->vm.attachCurrentFileRange(a,b);range=false};if(search)WorkspaceSearchDialog(vm){search=false}}

@Composable private fun AgentRound(r:ReadonlyAgentRound){Card(Modifier.fillMaxWidth()){Column(Modifier.padding(10.dp)){Text("Agent 第 ${r.index} 轮 · ${r.toolCalls.size} 个工具",style=MaterialTheme.typography.labelMedium);r.toolCalls.zip(r.toolOutcomes).forEach{(c,o)->Text("${c.name} · "+when(o){is AgentToolOutcome.Success->"${o.result.startOffset}-${o.result.endOffsetExclusive}/${o.result.totalCharacterCount}${if(o.result.complete)" 完整" else " 下一页 ${o.result.nextOffset}"}";is AgentToolOutcome.Failure->"失败"},style=MaterialTheme.typography.labelSmall)}}}
@Composable private fun RangeDialog2(d:ActiveWorkspaceDocument?,dismiss:()->Unit,confirm:(Int,Int)->Unit){var s by remember{mutableStateOf("1")};var e by remember{mutableStateOf("200")};val a=s.toIntOrNull();val b=e.toIntOrNull();AlertDialog(dismiss,{TextButton({confirm(a!!,b!!)},enabled=d!=null&&a!=null&&b!=null&&a>0&&b>=a){Text("附加")}},title={Text("附加文件范围")},text={Row{OutlinedTextField(s,{s=it},label={Text("起始行")},modifier=Modifier.weight(1f));OutlinedTextField(e,{e=it},label={Text("结束行")},modifier=Modifier.weight(1f))}},dismissButton={TextButton(dismiss){Text("取消")}})}
